version: 0.0
os: linux
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: run.sh
      timeout: 120
      runas: ec2-user
